/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Terminology Graph</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TerminologyGraph#getIri <em>Iri</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TerminologyGraph#getBoxStatements <em>Box Statements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTerminologyGraph()
 * @model
 * @generated
 */
public interface TerminologyGraph extends Module
{
  /**
   * Returns the value of the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Iri</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iri</em>' attribute.
   * @see #setIri(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTerminologyGraph_Iri()
   * @model
   * @generated
   */
  String getIri();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TerminologyGraph#getIri <em>Iri</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iri</em>' attribute.
   * @see #getIri()
   * @generated
   */
  void setIri(String value);

  /**
   * Returns the value of the '<em><b>Box Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.TerminologyBoxStatement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Box Statements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Box Statements</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTerminologyGraph_BoxStatements()
   * @model containment="true"
   * @generated
   */
  EList<TerminologyBoxStatement> getBoxStatements();

} // TerminologyGraph
